image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
environment:
  project: landing-page
  site: rogeruiz.srht.site
packages:
  - npm
  - hut
tasks:
  - install_dependencies: |
      pushd ${project}
      npm install
      popd
  - export: |
      pushd ${project}
      npm run build
      popd
  - package: |
      pushd ${project}
      tar -C out -cvz . > ../site.tar.gz
      popd
      file site.tar.gz
  - deploy: |
      hut pages publish -d $site site.tar.gz
