image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
secrets:
  - 5fd6bbf1-8791-4c37-8e1f-2d423d1c6a12
environment:
  URL: rog.gr
  GH_REPO: srht-landing-page
  GH_USER: rogeruiz
  SH_REPO: landing-page
packages:
  - nodejs
  - npm
  - hut
shell: true
tasks:
  - install_dependencies: |
      pushd ${SH_REPO}
      npm install
      popd
  - export: |
      pushd ${SH_REPO}
      npm run build
      popd
  - package: |
      pushd ${SH_REPO}
      tar -C out -cvz . > ../site.tar.gz
      popd
      file site.tar.gz
  - deploy: |
      hut pages publish -d ${URL} site.tar.gz
  - mirror-to-github: |
      cd ~/"${SH_REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${GH_REPO}"
