image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
environment:
  project: landing-page
  site: rogeruiz.srht.site
packages:
  - npm
tasks:
  - install_dependencies: |
      pushd ${project}
      npm install
      popd
  - export: |
      pushd ${project}
      npm run export
      popd
  - package: |
      pushd ${project}
      tar -C out -cvz . > ../site.tar.gz
      popd
      file site.tar.gz
  - deploy: |
      acurl -f "https://pages.sr.ht/publish/${site}" \
       -Fcontent=@site.tar.gz
